[package]
name = "welsib-httpd"
version = "0.1.0"
edition = "2024"

[dependencies]
crc = "3.2.1"
flate2 = "1.0.35"
num-bigint = "0.4.6"
openssl = "0.10.68"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
